version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: dev-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: developerstore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha1223
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
